"""Add user_info_id foreign key to chat_sessions

Revision ID: d00cc2d8ac40
Revises: b893b5a340fd
Create Date: 2025-04-25 14:52:48.273320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd00cc2d8ac40'
down_revision: Union[str, None] = 'b893b5a340fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_messages_user_info_id_fkey', 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'user_info_id')
    op.add_column('chat_sessions', sa.Column('user_info_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'chat_sessions', 'user_info', ['user_info_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'user_info_id')
    op.add_column('chat_messages', sa.Column('user_info_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('chat_messages_user_info_id_fkey', 'chat_messages', 'user_info', ['user_info_id'], ['id'])
    # ### end Alembic commands ###
