"""Add user_info_id to chat_sessions

Revision ID: 19a24a62c927
Revises: 
Create Date: 2025-04-25 13:06:03.248930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19a24a62c927'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faqs')
    op.add_column('chat_messages', sa.Column('user_info_id', sa.UUID(), nullable=True))
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('chat_messages', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('chat_messages', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('chat_messages_session_id_fkey', 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['session_id'], ['session_id'])
    op.create_foreign_key(None, 'chat_messages', 'user_info', ['user_info_id'], ['id'])
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('chat_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key('chat_messages_session_id_fkey', 'chat_messages', 'chat_sessions', ['session_id'], ['session_id'], ondelete='CASCADE')
    op.alter_column('chat_messages', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_messages', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('chat_messages', 'user_info_id')
    op.create_table('faqs',
    sa.Column('faq_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('faq_topic', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=10), server_default=sa.text("'en'::character varying"), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('faq_id', name='faqs_pkey')
    )
    # ### end Alembic commands ###
