"""Create faq_intent table

Revision ID: 4682ad6a0ea9
Revises: d00cc2d8ac40
Create Date: 2025-05-01 15:57:05.310805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4682ad6a0ea9'
down_revision: Union[str, None] = 'd00cc2d8ac40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faq_intent', sa.Column('bot_response', sa.Text(), nullable=False))
    op.drop_column('faq_intent', 'default_response')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faq_intent', sa.Column('default_response', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('faq_intent', 'bot_response')
    # ### end Alembic commands ###
